### PR TITLE
Refactor code to enforce stricter naming conventions

### PR DESCRIPTION
**Pull request by NickChapman**
Remove implied line continuation in favor of braces in most cases except the simplest
Move variable declarations closer to their first usage to eliminate mystery variables
Change StrawAlgo::cdaVertex from return type int to void since it always returns 0

### CODE REVIEW

**Comment by angelaromano** [comment]
Hi Nick, the branch has conflicts. I wonder whether you have pulled the latest modifications from NA62/na62-trigger-algorithms feature/straw_2016 before committing your modifications

**Comment by NickChapman** [comment]
Hi Angela,

I didn't but there was only Giovanna's commit after mine and it changed one
or two lines at most I believe. I can try to address the conflicts
tomorrow, but I don't think they should be too bad.

Best,
Nick

**Comment by angelaromano** [comment]
Hi Nick,

if you can do it is better..
I’m in Vietnam for a conference this week and I’m afraid I don’t really have time to work on this :(

Sorry about that,
Angela

**Comment by NickChapman** [comment]
Hi Angela,

No worries, I will try to clean up any issues tomorrow. Enjoy Vietnam!

Best,
Nick

**Comment by JonasKunze** [comment]
You might consider updating https://github.com/NA62/na62-trigger-algorithms/wiki/Conventions if you're not following them any more...

**Comment by NickChapman** [comment]
Hi Jonas, I will definitely update the conventions to clarify what is going
on here. Things got a bit tricky after we switched off of everything being
static.

Angela, I managed the merge conflicts and pushed back into my branch. I
believe it should all be taken care of. It was just from the one line that
Giovanna committed after me so nothing too troublesome.

**Comment by NickChapman** [comment]
Actually, I'm going to make one more change on the variable names so that the naming convention between classes and local variables is clearer.

**Comment by angelaromano** [comment]
Do you want me to do the merging now?

**Comment by NickChapman** [comment]
Ok it can merge now. It should now follow the naming conventions set out in the Conventions section of the wiki.

**Pull request merged**
