### PR TITLE
Updating the algorithm to check for overflows in order to prevent crashes

### PR DESCRIPTION
**Pull request by NickChapman**
Also includes a few minor edits to simply certain areas.

### CODE REVIEW

**Comment by angelaromano** [comment]
Hi Nick,
thanks for implemented these modifications. 
I have a couple of comments regarding StrawAlgo::abortProcessing(L1InfoToStorage\* l1Info)
- one should add l1Info->setL1StrawProcessed() to avoid the algorithm from being processed again on the same event when required within another trigger mask 
- if the idea here is to return a positive straw trigger word I would suggest to return 3 (instead of 1), which will be interpreted within L1TriggerProcessor as if the event fulfilled both L1 straw triggers for Kpnn and exotics data streams
  Does this make any sense to you?
  Cheers,
  Angela

**Comment by NickChapman** [comment]
Hi Angela, 
Sounds good. I wasn't sure what flags to set and what to return but that's why I bumped it out to abortProcessing. Give me one second and they'll be done.

**Comment by angelaromano** [comment]
Great, thanks!
I merged your modifications..don't forget to pull it from na62farmdev1 before the deploy :)
Cheers, Angela

**Comment by glehmannmiotto** [comment]
Ho Nick,
If you wish (or you haven't done it so far) can take care about the pull & deploy in about 1 hour.

## Giovanna

Giovanna Lehmann Miotto
CERN EP-DT-DI

On 8 Aug 2016, at 16:29, angelaromano <notifications@github.com<mailto:notifications@github.com>> wrote:

Great, thanks!
I merged your modifications..don't forget to pull it from na62farmdev1 before the deploy :)
Cheers, Angela

**Comment by NickChapman** [comment]
Hi Giovanna,

I don't believe I have access to na62farmdev1 so if you could do it that would be great.

Best,
Nick

**Comment by glehmannmiotto** [comment]
HI,
the new version is deployed (version 3.3.12). There is one configuration file which is different on dev1, but I left it as is.
na62-trigger-algorithms/l1/straw_algorithm/config/Spectrometer_online.2015.conf

Cheers
Giovanna

**Comment by pinzino** [comment]
perfect, thanks to everyone.
Make us know if there are some other crashes.

best regards,
Jacopo

Il 08/08/2016 17:54, glehmannmiotto ha scritto:

> HI,
> the new version is deployed (version 3.3.12). There is one 
> configuration file which is different on dev1, but I left it as is.
> na62-trigger-algorithms/l1/straw_algorithm/config/Spectrometer_online.2015.conf
> 
> Cheers
> Giovanna
>

**Comment by angelaromano** [comment]
Hi,
Thanks :) 
That's ok, we are not committing the configuration files every time.
That file should be sourcing the latest T0 files imported in farmdev1.
Maybe I'll ask Lorenza to import some more recent straw T0 files and change the Spectrometer_online2015.conf accordingly.

Cheers,
Angela

**Pull request merged**
